### PR TITLE
Offsets Now Fixed Properly and Delay for TriggerBot Fixed

### PR DESCRIPTION
**Pull request by kennyS-69420**
Just updated the offsets to save you some time going to be working on a script to automatically updated the offsets in the future using cs2-dumper, right now I am thinking about doing the script in python but if you have a suggestion for another language lmk

### CODE REVIEW

**Comment by Laidbak83** [comment]
Hello @kennyS-69420 do you have a discord ? To talk about it ?

**Comment by kennyS-69420** [comment]
> Hello @kennyS-69420 do you have a discord ? To talk about it ?

kenny_29296

**Comment by mildnsj** [comment]
nah you missed completely on viewangle
you should test your things out after you fix.

**Comment by zeroy2891** [comment]
i wish i knew what the f  are were you guys talking about:D

**Comment by CowNowK** [comment]
Why deleted the PlantedC4 address searching

**Comment by kennyS-69420** [comment]
My bad on the Plant C4 that was a mistake. Also no it did fix it if you go back and test it using FakeShotDelay it ends up having FakeShotDelay controls the time between shots and TriggerDelay does not change the initial reaction time at all....

**Comment by kennyS-69420** [comment]
> My bad on the Plant C4 that was a mistake. Also no it did fix it if you go back and test it using FakeShotDelay it ends up having FakeShotDelay controls the time between shots and TriggerDelay does not change the initial reaction time at all....

I literally just retested it

**Pull request merged**
